package gorpc

import (
	"fmt"
	"strings"

	pb "github.com/golang/protobuf/protoc-gen-go/descriptor"
	"github.com/golang/protobuf/protoc-gen-go/generator"
)

// Paths for packages used by code generated in this file,
// relative to the import_prefix of the generator.Generator.
const (
	gorpcServerPkgPath   = "github.com/lubanproj/gorpc"
	gorpcClientPkgPath   = "github.com/lubanproj/gorpc/client"
	gorpcInterceptorPkgPath = "github.com/lubanproj/gorpc/interceptor"
)

func init() {
	generator.RegisterPlugin(new(gorpc))
}

type gorpc struct {
	gen *generator.Generator
}

//Name returns the name of this plugin
func (p *gorpc) Name() string {
	return "gorpc"
}

//Init initializes the plugin.
func (p *gorpc) Init(gen *generator.Generator) {
	p.gen = gen
}

// Given a type name defined in a .proto, return its object.
// Also record that we're using it, to guarantee the associated import.
func (p *gorpc) objectNamed(name string) generator.Object {
	p.gen.RecordTypeUse(name)
	return p.gen.ObjectNamed(name)
}

// Given a type name defined in a .proto, return its name as we will print it.
func (p *gorpc) typeName(str string) string {
	return p.gen.TypeName(p.objectNamed(str))
}

// GenerateImports generates the import declaration for this file.
func (p *gorpc) GenerateImports(file *generator.FileDescriptor) {
}

// P forwards to g.gen.P.
func (p *gorpc) P(args ...interface{}) { p.gen.P(args...) }

// Generate generates code for the services in the given file.
func (p *gorpc) Generate(file *generator.FileDescriptor) {
	if len(file.FileDescriptorProto.Service) == 0 {
		return
	}
	_ = p.gen.AddImport(gorpcServerPkgPath)
	_ = p.gen.AddImport(gorpcClientPkgPath)
	_ = p.gen.AddImport(gorpcInterceptorPkgPath)
	_ = p.gen.AddImport("context")

	// generate all services
	for i, service := range file.FileDescriptorProto.Service {
		p.generateService(file, service, i)
	}
}

// generateService generates all the code for the named service
func (p *gorpc) generateService(file *generator.FileDescriptor, service *pb.ServiceDescriptorProto, index int) {
	originServiceName := service.GetName()
	serviceName := upperFirstLatter(originServiceName)
	p.P("// This following code was generated by protoc-gen-gorpc, DO NOT EDIT!!!")
	p.P()
	p.P("//================== server skeleton ===================")
	p.P(fmt.Sprintf(`type %[1]sService interface {
				`, serviceName))

	for _, method := range service.Method {
		p.generateServerInterfaceCode(method)
	}
	p.P("}")

	p.generateServiceDesc(service, file.GetPackage())
	for _, method := range service.Method {
		p.generateServerCode(service, method, file.GetPackage())
	}
	p.generateRegisterCode(service)

	p.P("//================== client stub===================")
	p.P(fmt.Sprintf(`//%[1]sClientProxy is a client proxy for service %[1]s.
		type %[1]sClientProxy interface {
	`))
	for _, method := range service.Method {
		p.generateClientInterfaceCode(method)
	}
	p.P("}")

	for _, method := range service.Method {
		p.generateClientCode(service, method, file.GetPackage())
	}
}

func (p *gorpc) generateRegisterCode(service *pb.ServiceDescriptorProto) {
	serviceName := upperFirstLatter(service.GetName())
	p.P(fmt.Sprintf(`
		func RegisterService(s *gorpc.Server, svr interface{}) {
			s.Register(_%s_serviceDesc, svr)
		}
	`, serviceName))
}

func (p *gorpc) generateServiceDesc(service *pb.ServiceDescriptorProto, pkgPath string) {

	serviceName := upperFirstLatter(service.GetName())
	p.P(fmt.Sprintf(`var _%s_serviceDesc = &gorpc.ServiceDesc{
		ServiceName: "%s.%s",
		HandlerType: (*%sService)(nil),
		Methods: []*gorpc.MethodDesc{
	`, serviceName, pkgPath,serviceName,serviceName))

	for _, method := range service.Method {
		methodName := upperFirstLatter(method.GetName())
		p.P(fmt.Sprintf(`{
			MethodName: "%s",
			Handler: %sService_%s_Handler,
		},`, methodName, serviceName, methodName))
	}

	p.P("},")
}

func (p *gorpc) generateServerInterfaceCode(method *pb.MethodDescriptorProto) {
	methodName := upperFirstLatter(method.GetName())
	inType := p.typeName(method.GetInputType())
	outType := p.typeName(method.GetOutputType())
	p.P(fmt.Sprintf("%s(ctx context.Context, req *%s)(*%s, error)"),
		methodName, inType, outType)
}

func (p *gorpc) generateServerCode(service *pb.ServiceDescriptorProto, method *pb.MethodDescriptorProto, pkgName string) {
	methodName := upperFirstLatter(method.GetName())
	serviceName := upperFirstLatter(service.GetName())
	inType := p.typeName(method.GetInputType())
	p.P(fmt.Sprintf(`
		func %sService_%s_Handler(ctx context.Context, svr interface{}, dec func(interface{} error,
			ceps []interceptor.ServerInterceptor)) (interface{} ,error){
			
			req := new(%s)
			if err := dec(req); err != nil {
				return nil, err	
			}

			if len(ceps) == 0 {
				return svr.(%sService).%s(ctx, req)
			}
			
			handler := func(ctx context.Context, reqbody interface{})(interface{}, error) {
				return svr.(%sService).%s(ctx, reqbody.(*%s))
			}
				
			return interceptor.ServerIntercept(ctx, req, ceps, handler)
		}
	`, serviceName, methodName, inType, serviceName, methodName, serviceName, methodName, inType))
}

func (p *gorpc) generateClientCode(service *pb.ServiceDescriptorProto, method *pb.MethodDescriptorProto, pkgName string) {
	methodName := upperFirstLatter(method.GetName())
	serviceName := upperFirstLatter(service.GetName())
	inType := p.typeName(method.GetInputType())
	outType := p.typeName(method.GetOutputType())
	p.P(fmt.Sprintf(`// %s is server rpc method as defined
		func (c *%sImpl) %s(ctx context.Context, req *%s, opts ...client.Option) (*%s ,error){
			
			callopts := make([]client.Option, 0, len(c.opts)+len(opts))
			callopts = append(callopts, c.opts...)
			callopts = append(callopts, opts...)

			rsp := &%s{}
			err := c.client.Invoke(ctx, req, rsp, "/%s.%s/%s", callopts...)
			if err != nil {
				return nil, err
			}

			return rsp, nil
		}
	`, methodName, serviceName, methodName, inType, outType, outType, pkgName, serviceName, methodName))
}

func (p *gorpc) generateClientInterfaceCode(method *pb.MethodDescriptorProto) {
	methodName := upperFirstLatter(method.GetName())
	inType := p.typeName(method.GetInputType())
	outType := p.typeName(method.GetOutputType())
	p.P(fmt.Sprintf("%s(ctx context.Context, req *%s, opts ...client.Option)(*%s, error)"),
		methodName, inType, outType)
	p.P()
}


// upperFirstLatter make the fisrt charater of given string  upper class
func upperFirstLatter(s string) string {
	if len(s) == 0 {
		return ""
	}
	if len(s) == 1 {
		return strings.ToUpper(string(s[0]))
	}
	return strings.ToUpper(string(s[0])) + s[1:]
}
